# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dnspyre < Formula
  desc ""
  homepage "https://github.com/Tantalor93/dnspyre"
  version "2.5.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Tantalor93/dnspyre/releases/download/v2.5.1/dnspyre_Darwin_arm64.tar.gz"
      sha256 "2b860a666a17060a26434940cccacea15c54ca52da406645939a1759631a1d0d"

      def install
        bin.install "dnspyre"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Tantalor93/dnspyre/releases/download/v2.5.1/dnspyre_Darwin_x86_64.tar.gz"
      sha256 "5f6a3e35be627f4560667b3eede957fe3f2ed2952cb187bfc2995f5f95368533"

      def install
        bin.install "dnspyre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Tantalor93/dnspyre/releases/download/v2.5.1/dnspyre_Linux_arm64.tar.gz"
      sha256 "0611c28c3d8b6de2695b5a6dd6026a2cf541136012cc4c21bf4c8e404058cd62"

      def install
        bin.install "dnspyre"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Tantalor93/dnspyre/releases/download/v2.5.1/dnspyre_Linux_x86_64.tar.gz"
      sha256 "71786cadbc87f533f1d1146e9a64b9c84bcf026b445a0c0b6d438ff733ddd8f6"

      def install
        bin.install "dnspyre"
      end
    end
  end
end
