# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dnspyre < Formula
  desc ""
  homepage "https://tantalor93.github.io/dnspyre/"
  version "2.21.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Tantalor93/dnspyre/releases/download/v2.21.0/dnspyre_darwin_arm64.tar.gz"
      sha256 "13be3e58f4b4fae5d19687574621f836db514f5eaf85f720b76ec1f7e52fef02"

      def install
        bin.install "dnspyre"
        bash_completion.install "completions/dnspyre.bash" => "_dnspyre"
        zsh_completion.install "completions/dnspyre.zsh" => "_dnspyre"
        man1.install Dir["manpages/*.1"]
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Tantalor93/dnspyre/releases/download/v2.21.0/dnspyre_darwin_amd64.tar.gz"
      sha256 "d9fa318068a3030821022396fd0307b8ac53f128294889df3625d29f6e445516"

      def install
        bin.install "dnspyre"
        bash_completion.install "completions/dnspyre.bash" => "_dnspyre"
        zsh_completion.install "completions/dnspyre.zsh" => "_dnspyre"
        man1.install Dir["manpages/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Tantalor93/dnspyre/releases/download/v2.21.0/dnspyre_linux_amd64.tar.gz"
      sha256 "73d09f709226c7fe3423cb8195322b588e3e015836de9ca6dfe281cdd0733120"

      def install
        bin.install "dnspyre"
        bash_completion.install "completions/dnspyre.bash" => "_dnspyre"
        zsh_completion.install "completions/dnspyre.zsh" => "_dnspyre"
        man1.install Dir["manpages/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Tantalor93/dnspyre/releases/download/v2.21.0/dnspyre_linux_arm64.tar.gz"
      sha256 "dd247082ddeeecea8f2b87d4f4ef29c8f7e4a66e9421be6e0c58ff53b0873d49"

      def install
        bin.install "dnspyre"
        bash_completion.install "completions/dnspyre.bash" => "_dnspyre"
        zsh_completion.install "completions/dnspyre.zsh" => "_dnspyre"
        man1.install Dir["manpages/*.1"]
      end
    end
  end
end
