# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dnspyre < Formula
  desc ""
  homepage "https://tantalor93.github.io/dnspyre/"
  version "2.14.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Tantalor93/dnspyre/releases/download/v2.14.1/dnspyre_Darwin_arm64.tar.gz"
      sha256 "1c6a97038fb7301ab96ca1497dba01be41aac8b7f8f42238a51481bd7e92b001"

      def install
        bin.install "dnspyre"
        bash_completion.install "completions/dnspyre.bash" => "_dnspyre"
        zsh_completion.install "completions/dnspyre.zsh" => "_dnspyre"
        man1.install Dir["manpages/*.1"]
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Tantalor93/dnspyre/releases/download/v2.14.1/dnspyre_Darwin_x86_64.tar.gz"
      sha256 "e13f5647f668aa314e8c896164ba4127e387ba51f645971ad1c815bf41ab70e4"

      def install
        bin.install "dnspyre"
        bash_completion.install "completions/dnspyre.bash" => "_dnspyre"
        zsh_completion.install "completions/dnspyre.zsh" => "_dnspyre"
        man1.install Dir["manpages/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Tantalor93/dnspyre/releases/download/v2.14.1/dnspyre_Linux_arm64.tar.gz"
      sha256 "72fd22ecba1dacfd1ee1c281226ee1e8d2356cbb7ee4c848d9330092f0704678"

      def install
        bin.install "dnspyre"
        bash_completion.install "completions/dnspyre.bash" => "_dnspyre"
        zsh_completion.install "completions/dnspyre.zsh" => "_dnspyre"
        man1.install Dir["manpages/*.1"]
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Tantalor93/dnspyre/releases/download/v2.14.1/dnspyre_Linux_x86_64.tar.gz"
      sha256 "9ed6fc2a08921a2371be2557948edd222179d3ebfe74ea196a5a0e821fdbf854"

      def install
        bin.install "dnspyre"
        bash_completion.install "completions/dnspyre.bash" => "_dnspyre"
        zsh_completion.install "completions/dnspyre.zsh" => "_dnspyre"
        man1.install Dir["manpages/*.1"]
      end
    end
  end
end
